### PR TITLE
metrics first pass , logging debug counters

### PR DESCRIPTION
**Pull request by jayunit100**
Heres a start for metrics in the scanner.  I kinda overdid it w/ counters before and after, just as a hacky way to debug an issue joel is seeing.

cc @sheppduck  @xenserverarmy

### CODE REVIEW

**Comment by jayunit100** [comment]
To be clear ; this is just for debugging ... but looks like Travis doesn't like it. Maybe we need a go get ./... or whatever in makefile

**Comment by xenserverarmy** [comment]
We need to discuss the design and intent here. If I understand what you're looking for, you're attempting to solve this in the wrong location. The `scanner` component of this project is intended to have zero third party dependencies which is why the build is failing. 

The likely correct location to solve this is in the controller and/or arbiter. Those components are permitted to have third party components, but they must be versioned with godeps.

**Comment by jayunit100** [comment]
Ok, Yeah I assumed there would be an ensuing discussion around the dep mgmt.    maybe add that constraint of third party deps to a README for the scanner.

**Comment by xenserverarmy** [comment]
I just looked at the code more (i.e. beyond just the build failure), and these changes also increase the attack surface for this container. Can you take some time and put together a full proposal for why instrumenting this container is needed, which metrics will be exposed, what problem the metrics are intended to solve, and most importantly - the impact of these changes on the attack surface.

Armed with your goals, we can iterate to find a solution which works for the role this `scanner` component plays in the system. If we need to iterate live, I'll UK time the next two days.

**Comment by jayunit100** [comment]
We can spin a pushgateway as an alternative w low attack surf

**Comment by sheppduck** [comment]
Guys to be clear this is for AREDHAT-69, which is all the http connections...  far more than the # of containers/image streams, etc.  Don't we just need a simple logging mechanism to post to the log something like: 
"I've connected to Hub (connection _blah_)"
"Connection _blah_ disconnected from Hub"
This way we can see just what connections are being made, but more importantly what connections are/are not not disconnecting.
I don't think we need a metric showing http connections, the Hub already is telling me/us that the scanners are connected...

**Comment by xenserverarmy** [comment]
@jayunit100 adding an additional requirement, such as a pushgateway, should be part of a design and then vetted with viability for production deployment. In the context of this PR, there are many other "gotchas", not the least of which the ephemeral nature of the `scanner` code.

Based on @sheppduck comments, I'm unclear on how the proposed metrics will attest to a potential Hub connection problem which isn't already captured with existing logging. What it does appear to be doing is providing metrics on how responsive the Docker engine/registry is to requests.

**Comment by jayunit100** [comment]
Hey guys - barely monitoring this, just saw the rest of the comments - thinking this should be closed - just a fire and forget PR to demonstrated how we might add metrics - I don't really know enough about the scanner right now to write a proposal around what it should / shouldn't count and measure .

At some point I'll try to add some to the arbiter - sounds like that is the central point for this sort of information to live ; as it decides wether a scan should happen or not ; based on the new dev docs that were merged -

**Pull request closed without merging**
